ALTER TABLE offers ALTER COLUMN rooms SET NOT NULL;
ALTER TABLE offers ALTER COLUMN area SET NOT NULL;
ALTER TABLE offers ALTER COLUMN price SET NOT NULL;
ALTER TABLE offers ALTER COLUMN price_per_m2 SET NOT NULL; 
ALTER TABLE offers ALTER COLUMN location SET NOT NULL;
ALTER TABLE offers ALTER COLUMN detail_url SET NOT NULL;